KodZrodlowy/web/airpollutionmonitor/urls.py
from airpollutionmonitor import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'airpollutionmonitor.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^$', 'app.views.index'),
    url(r'^index.html', 'app.views.index'),
    url(r'^show_plot.html', 'app.views.show_plot'),
    url(r'^air_pollutions.html$', 'app.views.air_pollutions', name='air_pollutions'),
    url(r'^stations.html$', 'app.views.stations', name='stations'),
)

KodZrodlowy/web/app/models.py
from django.db import models

class Station(models.Model):
    name = models.TextField()

class Pollution(models.Model):
    name = models.TextField()
    description = models.TextField()
    warn_level = models.FloatField()
    danger_level = models.FloatField()

class Measurement(models.Model):
    timestamp = models.DateTimeField()
    value = models.FloatField()
    pollution = models.ForeignKey('Pollution')
    station = models.ForeignKey('Station')

KodZrodlowy/web/app/forms.py
from django import forms

class ViewReportForm(forms.Form):
    """Klasa reprezentujaca formularz wyboru zakresu dat i stacji pomiarowej przez uzytkownika

    """


    stationid = forms.IntegerField(required=True)
    "Identyfikator stacji pomiarowej"

    start_date = forms.CharField(required=True)
    "Data poczatkowa na wykresie"

    end_date = forms.CharField(required=True)
    "Data koncowa na wykresie"

KodZrodlowy/web/app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from app.models import Pollution, Station, Measurement
from app.views_models import PlotData
from app.plot_renderer import PlotRenderer
from app.forms import ViewReportForm
import datetime


plotRenderer = PlotRenderer()
"Instancja klasy PlotRenderer do tworzenia wykresow"


def index(request):
    """Obsluguje zadanie HTTP dla glownej strony index.html

    """

    form = ViewReportForm() # An unbound form
    now = datetime.datetime.utcnow()
    form.start_date = datetime.datetime(now.year, now.month, now.day, 1)
    form.end_date = datetime.datetime(now.year, now.month, now.day, now.hour)

    stations = Station.objects.all()
    return render(request, 'app/index.html', {'form': form, 'stations': stations})


def air_pollutions(request):
    return render(request, 'app/air_pollutions.html')

def stations(request):
    return render(request, 'app/stations.html')


def show_plot(request):
    """Obsluguje zadanie HTTP dla strony wyswietlajacej wykres. Obsluguje zarowno metody GET jak i POST.

    """

    if request.method == 'POST': # If the form has been submitted...
        # ContactForm was defined in the previous section
        form = ViewReportForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            station_id = form.cleaned_data['stationid']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']

            station = Station.objects.filter(id=station_id).first()
            from datetime import datetime
            date1 = datetime.strptime(start_date, "%Y-%m-%d %H:%M")
            date2 = datetime.strptime(end_date, "%Y-%m-%d %H:%M")

            plot_file_path = plotRenderer.render_plot(station, date1, date2)
            return render(request, 'app/show_plot.html', {'plot_file_path': plot_file_path})
        else:
            return HttpResponseRedirect('index.html', {'is_form_invalid': True})
    else:
        return HttpResponseRedirect('index.html')

KodZrodlowy/web/templates/app/air_pollutions.html
{% extends 'base.html' %}

{% block title %} O zanieczyszczenaich powietrza {% endblock %}

    {% block content %}

        <div style="width: 80%; text-align: justify">

            <img src="{{ STATIC_URL }}images/malopolska390.jpeg"
            <br><br><br>

            <h5>Dwutlenek siarki SO2</h5>
            <p>Poziom dopuszczalny (norma) dla wartości średniej z doby (24 godziny),
                dla dwutlenku siarki (SO2) wynosi 125 µg/m3.
                Poziom dopuszczalny (norma) dla wartości średniej z jednej godziny,
                dla dwutlenku siarki (SO2) wynosi 350 µg/m3.</p>

            <br>

            <h5>Dwutlenek azotu</h5>
            <p>Poziom dopuszczalny (norma) dla wartości średniej z jednej
               godziny, dla dwutlenku azotu (NO2) wynosi 200 µg/m3.
               Poziom dopuszczalny (norma) dla wartości średniej z roku kalendarzowego dla
               dwutlenku azotu (NO2) wynosi 40 µg/m3.
               Dla dwutlenku azotu (NO2) nie jest określony poziom dopuszczalny (norma) dla wartości
              średniej z doby (24 godziny) i wartości średniej z miesišca.
            </p>

            <br>
            <h5>Tlenek węgla</h5>
            <p>Poziom dopuszczalny (norma) dla wartości średniej z ośmiu kolejnych godzin
               (ośmiogodzinna średnia kroczšca o kroku równym jedna godzina),
               dla tlenku węgla (CO) wynosi 10000 µg/m3.
               Dla tlenku węgla (CO) nie jest określony poziom dopuszczalny (norma) dla wartości średniej
              z jednej godziny, wartości średniej z doby (24 godziny) wartości średniej z miesiąca i wartości
              średniej z roku kalendarzowego. </p>

            <br>
            <h5>Ozon</h5>
            <p>Poziom dopuszczalny (norma) dla wartości średniej z ośmiu kolejnych godzin (ośmiogodzinna średnia kroczšca o kroku równym jedna godzina), dla ozonu (O3) wynosi 120 µg/m3.
                Dla ozonu (O3) nie jest określony poziom dopuszczalny (norma) dla wartości średniej z jednej godziny, wartości średniej z doby (24 godziny), wartości średniej z miesiąca i wartości średniej z roku kalendarzowego </p>

            <br>
            <h5>Pył zawieszony PM10</h5>
            <p>Poziom dopuszczalny (norma) dla wartości średniej z doby (24 godziny), dla pyłu zawieszonego PM10 wynosi 50 µg/m3.
            Poziom dopuszczalny (norma) dla wartości średniej z roku kalendarzowego dla pyłu zawieszonego PM10 wynosi 40 µg/m3.
            Dla pyłu zawieszonego PM10 nie jest określony poziom dopuszczalny (norma) dla wartości średniej z jednej godziny i wartości średniej z miesiąca
            </p>

            <br>
            <h5>Pył zawieszony PM2.5</h5>
            <p>Poziom dopuszczalny (norma) dla wartości średniej z roku kalendarzowego dla pyłu zawieszonego PM2,5 wynosi 25 µg/m3.
                Dla pyłu zawieszonego PM2,5 nie jest określony poziom dopuszczalny (norma) dla wartości średniej z jednej godziny, wartości średniej z doby (24 godziny) i wartości średniej z miesiąca.
            </p>
        <br><br><br><br><br>
        </div>

    {% endblock %}

KodZrodlowy/web/templates/app/index.html
{% extends 'base.html' %}

    {% block title %} Monitor zanieczyszczenia powietrza {% endblock %}

    {% block content %}

        <h1> Monitor zanieczyszczenia powietrza </h1>

        <div class="ui-widget">
            <div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em; ">
                <p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
                Wybierz stację pomiarową z listy oraz zakres dat, a nastepnie kliknij przycisk "Raport" aby wygenerować wykres.</p>
            </div>
        </div>

        <form action="show_plot.html" method="post">{% csrf_token %}

            <p><label for="id_stationid">Stacja pomiarowa:</label>
                <select id="id_stationid" name="stationid">
                    {% for station in stations %}
                        <option value="{{ station.id }}">{{ station.name }}</option>
                    {% endfor %}
                </select>
            </p>

            <p><label for="id_start_date">Data początkowa:</label>
                <input id="id_start_date" name="start_date" readonly="True" style="background-color: White; cursor: pointer"/>

            </p>

            <p><label for="id_end_date">Data końcowa:</label>
                <input id="id_end_date" name="end_date" readonly="True" style="background-color: White; cursor: pointer"/>

            </p>

            {% if form.end_date.errors %}
                <div class="ui-widget">
                    <div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
                        <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
                        Nieprawidłowy zakres dat - proszę wybrać datę początkową i końcową.</p>
                    </div>
                </div>
                <br/>
            {% endif %}

            {% if is_form_invalid %}
                <div class="ui-widget">
                    <div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;">
                        <p><span class="ui-icon ui-icon-error" style="float: left; margin-right: .3em;"></span>
                        Proszę wybrać zakres dat!</p>
                    </div>
                </div>
            {% endif %}

            <input id="button" type="submit" value="Raport"/>

        </form>


        <br/><br/>
        <div id="progressbarcontainer">
            <span>Trwa generowanie wykresu. To może chwilę potrwać...</span>
            <div id="progressbar"></div>
        </div>

        <script type="text/javascript">

         $(function() {

            $( "#button" ).button();

             $("#progressbarcontainer").hide();

            $( "#progressbar" ).progressbar({
                value: false
            });
         });

         //$( "#button" ).click(function() {
         //    $( "#progressbarcontainer" ).toggle("fast");
         //    $('#button').attr("disabled", true);
         //});

        $(document).ready(function() {
            $("#id_start_date").datetimepicker(
                {
                    beforeShow: function(input, inst) {
                        inst.dpDiv.css({ marginTop: -input.offsetHeight + 0 + 'px' });
                        inst.dpDiv.css({ marginLeft: input.offsetWidth + 10 + 'px' });
                    },
                    showMinutes: 'False',
                    minDate: -365,
                    firstDay: 1,
                    maxDate: 0,
                    closeText: 'OK',
                    timeText: 'Czas',
                    hourText: 'Godzina',
                    timeFormat: 'HH:mm',
                    dateFormat: 'yy-mm-dd',
                    monthNames: ['Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec', 'Sierpień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień'],
                    dayNames: [ 'Niedziela', 'Poniedziałek', 'Wtorek', 'Środa', 'Czwartek', 'Piątek', 'Sobota'],
                    dayNamesMin: ['N', 'Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'So']
                });

            $("#id_end_date").datetimepicker(
                {
                    beforeShow: function(input, inst) {
                        inst.dpDiv.css({ marginTop: -input.offsetHeight + 340 + 'px' });
                        inst.dpDiv.css({ marginLeft: input.offsetWidth + 10 + 'px' });
                    },
                    showMinutes: 'False',
                    minDate: -365,
                    firstDay: 1,
                    maxDate: 0,
                    closeText: 'OK',
                    timeText: 'Czas',
                    hourText: 'Godzina',
                    timeFormat: 'HH:mm',
                    dateFormat: 'yy-mm-dd',
                    monthNames: ['Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec', 'Sierpień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień'],
                    dayNames: [ 'Niedziela', 'Poniedziałek', 'Wtorek', 'Środa', 'Czwartek', 'Piątek', 'Sobota'],
                    dayNamesMin: ['N', 'Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'So']
                });
        });
    </script>

    {% endblock %}

KodZrodlowy/web/templates/app/show_plot.html
{% extends 'base.html' %}

{% block title %} Monitor zanieczyszczenia powietrza {% endblock %}

    {% block content %}

        <script type="text/javascript">

             $(function() {

                $( "#back" ).button();

             });
        </script>
<br><br>
        <img src="{{ STATIC_URL }}{{ plot_file_path }}" style="margin-top: -50px"/>

         <a href="javascript: history.back()" id="back">Powrót do strony głównej</a>

    {% endblock %}

KodZrodlowy/web/templates/app/stations.html
{% extends 'base.html' %}

{% block title %} Stacje pomiarowe {% endblock %}

    {% block content %}



    {% endblock %}

KodZrodlowy/web/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Untitled{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }

      .ui-datepicker {
          font-size: 9pt !important;
      }

    </style>

    <link href="{{ STATIC_URL }}css/ui-lightness/jquery-ui-1.10.4.custom.css" rel="stylesheet">
    <script src="{{ STATIC_URL }}js/jquery-1.10.2.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui-1.10.4.custom.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui-timepicker-addon.js"></script>

    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/bootstrap-responsive.css" rel="stylesheet">

    {% block extrahead %}
    {% endblock %}

  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Air Pollution Monitor</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><a href="/">Strona główna</a></li>
              <!-- <li><a href="{% url 'stations' %}">Stacje pomiarowe</a></li> -->
              <li><a href="{% url 'air_pollutions' %}">O zanieczyszczeniach powietrza</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div id="messages">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            <a class="close" data-dismiss="alert">×</a>
            {{message}}
          </div>
        {% endfor %}
      {% endif %}
    </div>

    <div class="container">
    {% block content %}
    {% endblock %}
    </div> <!-- /container -->
  </body>
</html>